name: Deploy to Heroku

on:
  workflow_run:
    workflows: ["PyTest"]
    types: [completed]

jobs:
  deploy:
    if: |
      github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.head_branch == github.event.repository.default_branch
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Heroku
        uses: dentarg/heroku@v1
        with:
          app: simplycalendar
          key: 77955c67-377c-497b-93f2-f3493b2b58f6
